import os
import sys
import time
import socket
import logging
import threading
import ssl
import numpy as np

# ---------------------------------------------------------
# DOCKER-PROOF PATH INJECTION
# ---------------------------------------------------------
if '/app' not in sys.path:
    sys.path.insert(0, '/app')

from src.network.ipc import send_msg, recv_msg
from src.network.fog_bridge import FogBridgeClient, FogBridgeServer

# =====================================================================
# Logger Configuration
# =====================================================================
logger = logging.getLogger("ZTA_Comm_Test")
logger.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s | %(levelname)-8s | %(message)s', datefmt='%H:%M:%S')
ch.setFormatter(formatter)
logger.addHandler(ch)

def print_separator(title: str):
    print("\n" + "="*80)
    print(f"🚀 TEST: {title}")
    print("="*80)

def find_free_port() -> int:
    """Dynamically finds an open port on the OS to prevent test collisions."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        return s.getsockname()[1]

# =====================================================================
# Cryptographic Paths (Generated by setup_security.sh)
# =====================================================================
CERTS_DIR = "/app/src/network/certs"

# Cloud Tier PKI
CLOUD_CA = f"{CERTS_DIR}/cloud_ca/ca.crt"
CLOUD_CERT = f"{CERTS_DIR}/cloud_server/certificates.pem"
CLOUD_KEY = f"{CERTS_DIR}/cloud_server/private-key.pem"

# Edge/Fog Tier PKI
EDGE_CA = f"{CERTS_DIR}/edge_ca/ca.crt"
FOG_CERT = f"{CERTS_DIR}/fog_1/nginx.crt"
FOG_KEY = f"{CERTS_DIR}/fog_1/nginx.key"
EDGE_CERT = f"{CERTS_DIR}/edge_1_1/client.crt"
EDGE_KEY = f"{CERTS_DIR}/edge_1_1/client.key"


def run_ssl_handshake_test(server_ctx: ssl.SSLContext, client_ctx: ssl.SSLContext, test_name: str, 
                           expect_success: bool = True, raw_client: bool = False):
    """
    Helper function to spin up a threaded socket server and client to test TLS boundaries.
    """
    port = find_free_port()
    server_ready = threading.Event()
    handshake_result = {"server_error": None, "client_error": None, "success": False}

    def server_task():
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            sock.bind(('127.0.0.1', port))
            sock.listen(1)
            server_ready.set()
            
            try:
                conn, addr = sock.accept()
                conn.settimeout(2.0)
                # Apply the SSL wrapper. If the client fails authentication, this throws an SSLError
                with server_ctx.wrap_socket(conn, server_side=True) as secure_conn:
                    secure_conn.sendall(b"SECURE_PAYLOAD")
                    handshake_result["success"] = True
            except Exception as e:
                handshake_result["server_error"] = str(e)

    t_server = threading.Thread(target=server_task)
    t_server.start()
    server_ready.wait(timeout=2.0)

    try:
        with socket.create_connection(('127.0.0.1', port), timeout=2.0) as raw_sock:
            if raw_client:
                # 🛑 CRACKING TEST: Attempt to read data directly without performing the SSL Handshake
                raw_sock.sendall(b"GIVE ME DATA")
                data = raw_sock.recv(1024)
                if b"SECURE_PAYLOAD" in data:
                    handshake_result["client_error"] = "CRITICAL: Read plaintext payload over raw socket!"
            else:
                # 🟢 NORMAL TEST: Apply client SSL wrapper
                with client_ctx.wrap_socket(raw_sock, server_hostname="localhost") as secure_client:
                    data = secure_client.recv(1024)
    except Exception as e:
        handshake_result["client_error"] = str(e)

    t_server.join(timeout=2.0)

    # Evaluate against expectations
    if expect_success:
        if handshake_result["success"]:
            logger.info(f"✅ {test_name}: Successful handshake and transfer.")
        else:
            logger.error(f"❌ {test_name}: Expected success but failed! Server Err: {handshake_result['server_error']} | Client Err: {handshake_result['client_error']}")
            sys.exit(1)
    else:
        if not handshake_result["success"]:
            logger.info(f"✅ {test_name}: Connection correctly rejected by cryptography. (Err: {handshake_result['server_error'] or handshake_result['client_error']})")
        else:
            logger.error(f"❌ {test_name}: Expected failure but handshake succeeded! Security boundary breached.")
            sys.exit(1)


def run_communication_diagnostics():
    print("\n" + "#"*80)
    print("### STARTING TRANSPORT & CRYPTOGRAPHY INTEGRATION TEST ###")
    print("#"*80)

    if not os.path.exists(CLOUD_CA) or not os.path.exists(EDGE_CA):
        logger.error("❌ Certificates not found. Please run boot_network_docker.sh without --insecure first.")
        sys.exit(1)

    # =====================================================================
    # CATEGORY 1: FOG <-> CLOUD (Standard TLS)
    # =====================================================================
    print_separator("1. FOG <-> CLOUD BOUNDARY (TLS 1.3)")
    
    # Context 1: Valid Cloud Server (Loads its cert)
    cloud_server_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    cloud_server_ctx.load_cert_chain(certfile=CLOUD_CERT, keyfile=CLOUD_KEY)
    
    # Context 2: Valid Fog Client (Verifies Cloud Server using Cloud CA)
    fog_client_ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    fog_client_ctx.load_verify_locations(cafile=CLOUD_CA)
    fog_client_ctx.check_hostname = False # Bypass DNS check for localhost testing

    # TEST 1.1: Valid Connection
    logger.debug("Testing valid encrypted channel...")
    run_ssl_handshake_test(cloud_server_ctx, fog_client_ctx, "Fog<->Cloud Authentication", expect_success=True)

    # TEST 1.2: Cracking / Eavesdropping
    logger.debug("Testing eavesdropping with a raw unencrypted TCP socket...")
    run_ssl_handshake_test(cloud_server_ctx, fog_client_ctx, "Fog<->Cloud Eavesdropping Defeated", expect_success=False, raw_client=True)

    # TEST 1.3: Identity Spoofing (Rogue Cloud Server)
    logger.debug("Testing Cloud Server Spoofing (Rogue Server using Edge PKI)...")
    # Build a rogue server context using the FOG certificate instead of the CLOUD certificate
    rogue_cloud_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    rogue_cloud_ctx.load_cert_chain(certfile=FOG_CERT, keyfile=FOG_KEY)
    
    # The Fog Client strictly demands a signature from the CLOUD CA. It should reject the FOG cert.
    run_ssl_handshake_test(rogue_cloud_ctx, fog_client_ctx, "Fog<->Cloud Rogue Server Rejected", expect_success=False)


    # =====================================================================
    # CATEGORY 2: EDGE <-> FOG (Mutual TLS via NGINX)
    # =====================================================================
    print_separator("2. EDGE <-> FOG BOUNDARY (Strict mTLS)")
    
    # Context 1: Valid Fog NGINX Server (Loads cert, DEMANDS Client Cert signed by Edge CA)
    nginx_server_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    nginx_server_ctx.load_cert_chain(certfile=FOG_CERT, keyfile=FOG_KEY)
    nginx_server_ctx.verify_mode = ssl.CERT_REQUIRED # STRICT mTLS ENFORCEMENT
    nginx_server_ctx.load_verify_locations(cafile=EDGE_CA) 

    # Context 2: Valid Edge Client (Loads cert, DEMANDS Server Cert signed by Edge CA)
    edge_client_ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    edge_client_ctx.load_cert_chain(certfile=EDGE_CERT, keyfile=EDGE_KEY)
    edge_client_ctx.load_verify_locations(cafile=EDGE_CA)
    edge_client_ctx.check_hostname = False

    # TEST 2.1: Valid mTLS Connection
    logger.debug("Testing valid bidirectional mTLS authentication...")
    run_ssl_handshake_test(nginx_server_ctx, edge_client_ctx, "Edge<->Fog Mutual Authentication", expect_success=True)

    # TEST 2.2: Cracking / Eavesdropping
    logger.debug("Testing eavesdropping on the Edge/Fog bridge...")
    run_ssl_handshake_test(nginx_server_ctx, edge_client_ctx, "Edge<->Fog Eavesdropping Defeated", expect_success=False, raw_client=True)

    # TEST 2.3: Identity Spoofing (Both Directions)
    logger.debug("Testing Edge Spoofing (Rogue Edge using Cloud PKI)...")
    # Rogue Edge uses the Cloud cert. NGINX will reject it because it wasn't signed by the Edge CA.
    rogue_edge_ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    rogue_edge_ctx.load_cert_chain(certfile=CLOUD_CERT, keyfile=CLOUD_KEY)
    rogue_edge_ctx.load_verify_locations(cafile=EDGE_CA)
    rogue_edge_ctx.check_hostname = False
    run_ssl_handshake_test(nginx_server_ctx, rogue_edge_ctx, "Edge<->Fog Rogue Edge Client Rejected", expect_success=False)

    logger.debug("Testing Fog Spoofing (Rogue Fog using Cloud PKI)...")
    # Rogue Fog uses the Cloud cert. Edge client will reject it.
    rogue_nginx_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    rogue_nginx_ctx.load_cert_chain(certfile=CLOUD_CERT, keyfile=CLOUD_KEY)
    rogue_nginx_ctx.verify_mode = ssl.CERT_REQUIRED
    rogue_nginx_ctx.load_verify_locations(cafile=EDGE_CA)
    run_ssl_handshake_test(rogue_nginx_ctx, edge_client_ctx, "Edge<->Fog Rogue NGINX Server Rejected", expect_success=False)


    # =====================================================================
    # CATEGORY 3: CUSTOM IPC BRIDGE (fog_bridge.py / ipc.py)
    # =====================================================================
    print_separator("3. INTERNAL IPC BRIDGE (Fog <-> Fog Supernode)")
    logger.debug("Testing continuous state stability and complex weight transfer over plaintext localhost sockets.")

    ipc_port = find_free_port()
    os.environ["FOG_SERVER_HOST"] = "127.0.0.1"
    
    bridge_server = FogBridgeServer(logger, "[TEST_SRV]", ipc_port, socket_timeout=5.0)
    bridge_client = FogBridgeClient(logger, "[TEST_CLI]", ipc_port, socket_timeout=5.0)

    # Generate complex simulated model weights (list of Numpy NDArrays)
    simulated_weights = [
        np.random.rand(128, 256).astype(np.float32), 
        np.array([1.0, 3.14, 42.0], dtype=np.float64)
    ]

    server_exceptions = []

    def bridge_server_task():
        # TEST 3.1 & 3.2: Run 3 consecutive rounds to prove the socket binds and drops cleanly without deadlocking
        for round_num in [1, 2, 3]:
            try:
                logger.debug(f"[IPC SERVER] Waiting for START command for round {round_num}...")
                received_round = bridge_server.wait_for_start()
                
                if received_round == round_num:
                    logger.debug(f"[IPC SERVER] START {received_round} validated. Injecting weights into stream...")
                    bridge_server.relay_weights(simulated_weights)
                else:
                    server_exceptions.append(f"Expected round {round_num}, got {received_round}")
            except Exception as e:
                server_exceptions.append(str(e))

    t_ipc = threading.Thread(target=bridge_server_task)
    t_ipc.start()
    time.sleep(0.2) # Allow server to bind

    # Client initiates the 3 consecutive rounds
    client_success_count = 0
    for round_num in [1, 2, 3]:
        received_weights, status, _ = bridge_client.execute_round(current_round=round_num)
        
        # Verify weight transfer math
        if status == 1 and len(received_weights) == 2:
            match_1 = np.array_equal(received_weights[0], simulated_weights[0])
            match_2 = np.array_equal(received_weights[1], simulated_weights[1])
            
            if match_1 and match_2:
                client_success_count += 1
                logger.debug(f"[IPC CLIENT] Round {round_num} complete. Mathematical equivalence verified.")
            else:
                logger.error(f"❌ IPC Bridge data corruption during round {round_num}.")
        
        time.sleep(0.1) # Small buffer between socket connections

    t_ipc.join(timeout=2.0)

    if client_success_count == 3 and not server_exceptions:
        logger.info("✅ IPC Custom Bridge: Successful consistency across multiple rounds. Tensors serialized natively.")
    else:
        logger.error(f"❌ IPC Custom Bridge Failed. Success count: {client_success_count}/3. Server Exceptions: {server_exceptions}")
        sys.exit(1)

    print("\n" + "#"*80)
    print("🎉 ALL COMMUNICATION & CRYPTOGRAPHY TESTS PASSED. 🎉")
    print("#"*80 + "\n")

if __name__ == "__main__":
    run_communication_diagnostics()